# Generated by Django 6.0.4 on 2026-04-17 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('option', 'Option'), ('future', 'Future'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('index', 'Index ETF')], default='stock', max_length=10)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit')], default='market', max_length=10)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('option_type', models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.order')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.tradingaccount')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('option', 'Option'), ('future', 'Future'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('index', 'Index ETF')], default='stock', max_length=10)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('contract_size', models.IntegerField(default=100, help_text='Multiplier (100 for options, varies for futures)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.tradingaccount')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='portfolio.tradingaccount'),
        ),
    ]
